### ISSUE TITLE
S3TransferManager does not resume data uploads after pause / resume

### ISSUE THREAD

**Issue by digitalpbk** [aws/aws-sdk-ios-v1#46]
S3TransferManager.m line 
//Don't save metadata if request doesn't have a filename for put or a targetFilePath for get

My put object requests are called with NSData, so they are not resumed after a pause.

Write the NSData to the metadata file perhaps?

**Comment by kredden** [comment]
The TransferManager was rewritten in v2 of the SDK and this problem has not been reported anymore.
