### ISSUE TITLE
S3 single part throttling stream uploading ?

### ISSUE THREAD

**Issue by Bhushan30** [aws/aws-sdk-ios-v1#54]
How we can upload throttling stream using S3 aws-sdk-ios.
The S3UploadInputStream was deprecated after the release of iOS6. So what is best solution to upload throttling stream to amazon server?

**Comment by kredden** [comment]
The TransferManager was rewritten in v2 of the SDK (https://github.com/aws/aws-sdk-ios), please report any issues you have there.
