### ISSUE TITLE
Support ConditionalOperator in DynamoDBScanRequest?

### ISSUE THREAD

**Issue by zoul** [aws/aws-sdk-ios-v1#58]
Currently the filter conditions set for a `DynamoDBScanRequest` are evaluated using the `AND` operator: they all have to be true for the item to be included in the scan results. The API supports a `ConditionalOperator` field ([see docs](http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Scan.html#DDB-Scan-request-ConditionalOperator)) that can be used to change this behaviour to `OR`. The iOS SDK doesn’t seem to implement the `ConditionalOperator` field. I’d be happy to write the code and submit a pull request, would you merge it?

**Comment by kredden** [comment]
The DynamoDBObjectMapper in the v2 version of the SDK supports this (https://github.com/aws/aws-sdk-ios).
