### ISSUE TITLE
Large file multi-part upload in version 1.7.1 with S3TransferManager

### ISSUE THREAD

**Issue by slobo-showbie** [aws/aws-sdk-ios-v1#59]
I recently updated to version 1.7.1 of the AWS iOS SDK.  Uploads for large files do not work.  I am using S3TransferManager with operationQueue.maxConcurrentOperationCount = 2 and mulltipartUploadThreshold = 5 \* 1024 \* 1024.  1.7.0 works without issue.

**Comment by kredden** [comment]
TransferManager was rewritten in v2 of the SDK, please report any issues in that repo (https://github.com/aws/aws-sdk-ios).
