### ISSUE TITLE
Plans to implement SSE-C ? 

### ISSUE THREAD

**Issue by freak4pc** [aws/aws-sdk-ios-v1#62]
Amazon S3 introduced SSE-C For encrypting objects with client-provided-keys, 
Do you have any plans of implementing this in your SDK ?

http://docs.aws.amazon.com/AmazonS3/latest/dev/ServerSideEncryptionCustomerKeys.html?sc_ichannel=em&sc_icountry=Global&sc_icampaigntype=launch&sc_icampaign=em_118914880&sc_idetail=em_8031287915&ref_=pe_411040_118914880_8

Shai

**Comment by kredden** [comment]
This functionality is supported in v2 of the SDK (https://github.com/aws/aws-sdk-ios).

**Comment by freak4pc** [comment]
a response delayed in 3 years :p but thank you !
