### ISSUE TITLE
Threading issue

### ISSUE THREAD

**Issue by undiscovrd** [aws/aws-sdk-ios-v1#65]
Description:

I have three controllers. The first is a tweaked version of AVCAM offered by Apple that involves using the AVFramework to create a custom photo/video capture controller, a controller that allows a user to annotate a photo/video and then another controller that I display once this annotating is done. The controller flow is done in this order, with a user capturing the content, annotating, and then displaying this last controller.

The issue the arises when either transitioning from the mark up to the last view controller or progressively dismissing the stack (i.e. dismissing the last controller, loading the view from the annotate controller that contains the s3 code and then dismissing this to return to the first (camera) controller). I perform a putobject request on the mark up (2nd in stack) controller. This has been working well until recently when I encounter this issue:
![screen shot 2014-07-28 at 3 06 56 pm](https://cloud.githubusercontent.com/assets/5178101/3728035/7ffb2e74-16a4-11e4-84dd-f1e5ad32ada1.png)

![screen shot 2014-07-28 at 3 07 04 pm](https://cloud.githubusercontent.com/assets/5178101/3728038/896927b8-16a4-11e4-982c-2ec353145eb2.png)

![screen shot 2014-07-28 at 3 07 07 pm](https://cloud.githubusercontent.com/assets/5178101/3728040/8f5acc26-16a4-11e4-97d8-e9ad6ca6c6d2.png)

This does not crash all threads, as my camera controller preview layer is still reading a buffer. However, the main thread seems to halt as no more selectors or actions can be received. I know v2 is out and I should be developing with that but I need a working app now. This seems to just be something to do with the way aws threads the upload response handlers so I am seeking on advice on how to do this. For reference I only have didcompleteWithResponse: delegate method written and not didSendBodyData:.

**Comment by kredden** [comment]
The TransferManager was rewritten in v2 of the SDK, please report any issues in that repo (https://github.com/aws/aws-sdk-ios).
